#!/bin/bash
# 
# Installation script which setup up an Ubuntu Trusty machine to use this
# xmonad configuration. 
#
# WARNING!!! 
# * This has only been tested on a limited number of machines running 
#   Ubuntu 14.04 64-bit.
# * This is not a sophisticated installation script by any stretch 
#   of the imagination. 
# * I take no responsibility if this overwrites any configuration settings 
#   or otherwise messes up your system. 
#
# Please review the readme file to find out exactly what it does and does not 
# do. Or, visit the repository for more information: 
# https://github.com/cestdiego/xmonad-ubuntu
# 
# Author: Diego Berrocal 
# 
# 
# This script is heavily inspired by the one from @davidbrewer
# 
# 

echo "Installation Starting\n"

sudo apt-add-repository ppa:peterlevi/ppa -y;

echo "\n Updating repositories\n"
sudo apt-get update;

echo "\n Installing required packages...\n"
sudo apt-get install xmonad libghc-xmonad-dev libghc-xmonad-contrib-dev xmobar nitrogen \
     compton stalonetray moreutils consolekit ssh-askpass-gnome xbacklight ranger htop xsel \
     acpi rxvt-unicode-256color dmenu scrot mplayer variety conky sysstat xdotool dzen2 -y ;

echo "\n Creating xmonad xsession configuration...\n"
sudo mv /usr/share/xsessions/xmonad.desktop /usr/share/xsessions/xmonad.desktop.original ;
sudo cp ~/.xmonad/xmonad.desktop /usr/share/xsessions ;
sudo cp ~/.xmonad/images/custom_xmonad_badge.png /usr/share/unity-greeter;

echo "\n Symbolic Linking .urxvt configuration to home directory \n"
ln -s ~/.xmonad/.urxvt ~/.urxvt;

echo "\n Backing up .Xresources as .Xresources.old you can check the differences for yourself\n"
mv ~/.Xresources{,.old} ;

echo "Symbolic Linking .Xresources"
ln -s ~/.xmonad/.Xresources ~/.Xresources;

echo "Symbolic Linking Compton Configuration File"
ln -s ~/.xmonad/compton.conf ~/.config/compton.conf;


echo "Linking to customized gnome 2 configuration..."
mv ~/.gtkrc-2.0 ~/gtkrc-2.0.original;
ln -s ~/.xmonad/.gtkrc-2.0 ~/.gtkrc-2.0;

sed -i "s/\/home\/io/\/home\/$USER/g" .conky_dzen.bak scripts/*.sh
