#!/bin/bash
foreground=$1
background=$2
font=$3

# Check to see if external is connected
if [[ -z `xrandr | grep " connected" | grep 'VGA'` ]]; then
	conky -qc /home/io/.xmonad/.conky_dzen | dzen2 \
            -x '1000' -y '0' \
            -w '705' -h '24' \
            -ta 'r' \
            -bg $background \
            -fg $foreground \
            -fn $font \
            -dock &
else 
	#nitrogen --restore
	conky -qc /home/io/.xmonad/.conky_dzen | dzen2 \
            -x '1000' -y '0' \
            -w '2700' -h '24' \
            -ta 'r' \
            # -bg $background \
            # -fg $foreground \
            # -fn $font \
            -dock &
	#conky -qc /home/hackspace/.xmonad/.conky_dzen2 | dzen2 -x '1200' -w '720' -h '14' -ta 'r' -bg $background -fg $foreground -y '0' -fn $font -dock &
	#conky -qc /home/hackspace/.xmonad/.conky_dzen3 | dzen2 -x '1200' -w '720' -h '14' -ta 'r' -bg $background -fg $foreground -y '0' -fn $font -dock &
fi
